credentials:
  usernames:
    admin:
      name: Admin User
      password: '$2b$12$KIXx3wDpiRkIkG8S8wlVOOOeD3ZTPKllVebfPy2OD6qsVWR8n5Zz6'  # 'admin123'
      role: admin
    john:
      name: John Doe
      password: '$2b$12$od5ZkAwq4vN6D7BbRYwHae7zXsl.x5t9C/NMFFZQzKxvo6/3IUP4i'  # 'john123'
      role: viewer

cookie:
  name: asset_dashboard
  key: abcdefg
  expiry_days: 1

preauthorized:
  emails: []
